#ifndef QUICKSYSTEMTRAYICONGLOBAL_H
#define QUICKSYSTEMTRAYICONGLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QT_BUILD_QUICKSYSTEMTRAYICON_LIB)
#  define Q_QUICKSYSTEMTRAYICON_EXPORT Q_DECL_EXPORT
#else
#  define Q_QUICKSYSTEMTRAYICON_EXPORT Q_DECL_IMPORT
#endif

#endif // QUICKSYSTEMTRAYICONGLOBAL_H
